import { type WorkflowExecutionInfo } from '@/__generated__/proto-ts/uber/cadence/api/v1/WorkflowExecutionInfo';

export const mockBatchOperationWorkflows: Array<WorkflowExecutionInfo> = [
  {
    workflowExecution: {
      workflowId: 'mock-batch-action-id-1',
      runId: 'mock-batch-action-run-id-1',
    },
    type: { name: 'cadence-sys-batch-workflow-v2' },
    startTime: { seconds: '1717408148', nanos: 258000000 },
    closeTime: { seconds: '1717409148', nanos: 258000000 },
    closeStatus: 'WORKFLOW_EXECUTION_CLOSE_STATUS_COMPLETED',
    historyLength: '100',
    parentExecutionInfo: null,
    executionTime: { seconds: '1717408150', nanos: 0 },
    memo: null,
    searchAttributes: null,
    autoResetPoints: null,
    taskList: 'cadence-sys-batcher-tasklist',
    isCron: false,
    updateTime: { seconds: '1717408200', nanos: 0 },
    partitionConfig: {},
    taskListInfo: null,
    activeClusterSelectionPolicy: null,
    cronOverlapPolicy: 'CRON_OVERLAP_POLICY_INVALID',
    cronSchedule: '',
    executionStatus: 'WORKFLOW_EXECUTION_STATUS_INVALID',
    scheduledExecutionTime: null,
  },
  {
    workflowExecution: {
      workflowId: 'mock-batch-action-id-2',
      runId: 'mock-batch-action-run-id-2',
    },
    type: { name: 'cadence-sys-batch-workflow-v2' },
    startTime: { seconds: '1717400000', nanos: 0 },
    closeTime: null,
    closeStatus: 'WORKFLOW_EXECUTION_CLOSE_STATUS_INVALID',
    historyLength: '5',
    parentExecutionInfo: null,
    executionTime: { seconds: '1717400002', nanos: 0 },
    memo: null,
    searchAttributes: null,
    autoResetPoints: null,
    taskList: 'cadence-sys-batcher-tasklist',
    isCron: false,
    updateTime: { seconds: '1717400050', nanos: 0 },
    partitionConfig: {},
    taskListInfo: null,
    activeClusterSelectionPolicy: null,
    cronOverlapPolicy: 'CRON_OVERLAP_POLICY_INVALID',
    cronSchedule: '',
    executionStatus: 'WORKFLOW_EXECUTION_STATUS_INVALID',
    scheduledExecutionTime: null,
  },
];
