const WORKFLOW_ACTIONS_NON_RUNNABLE_STATUSES_CONFIG = [
  'NOT_RUNNABLE_WORKFLOW_CLOSED',
] as const satisfies Array<`NOT_RUNNABLE_${string}`>;

export default WORKFLOW_ACTIONS_NON_RUNNABLE_STATUSES_CONFIG;
