const SCHEDULE_ACTIONS_NON_RUNNABLE_STATUSES_CONFIG = [
  'NOT_RUNNABLE_SCHEDULE_ALREADY_PAUSED',
  'NOT_RUNNABLE_SCHEDULE_NOT_PAUSED',
] as const satisfies Array<`NOT_RUNNABLE_${string}`>;

export default SCHEDULE_ACTIONS_NON_RUNNABLE_STATUSES_CONFIG;
