const WORKFLOW_ACTIONS_DISABLED_VALUES_CONFIG = [
  'DISABLED_DEFAULT',
  'DISABLED_UNAUTHORIZED',
] as const satisfies Array<`DISABLED_${string}`>;

export default WORKFLOW_ACTIONS_DISABLED_VALUES_CONFIG;
